### ISSUE TITLE
Duplicate Operation Paging Parameters (MaxResults and NextToken)

### ISSUE THREAD

**Issue by ggallotti** [APIs-guru/aws2openapi#18]
Some actions have duplicate parameters with different casing. 
I think that they are referring to the same parameter.

Example: MaxResults and NextToken.

```
'/#Action=DescribeSpotFleetRequests':
    post:
      operationId: DescribeSpotFleetRequests
     ...
      parameters:
        - name: maxResults
          in: query
          required: false
          description: 'The maximum number of results to return in a single call.....value.'
          type: integer
        - name: nextToken
          in: query
          required: false
          description: The token for the next set of results.
          type: string
  ....
        - name: MaxResults
          type: string
          in: query
          description: Pagination limit
          required: false
        - name: NextToken
          type: string
          in: query
          description: Pagination token
          required: false
```

[https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/amazonaws.com/ec2/2016-11-15/swagger.yaml](url)
