### ISSUE TITLE
The "operationId" field shouldn't have spaces

### ISSUE THREAD

**Issue by sverch** [APIs-guru/aws2openapi#33]
While the [spec doesn't specifically say that spaces aren't allowed](https://swagger.io/specification/), it did say this:

operationId | string | Unique string used to identify the operation. The id MUST be unique  among all operations described in the API. The operationId value is case-sensitive.  Tools and libraries MAY use the operationId to uniquely identify an  operation, therefore, it is RECOMMENDED to follow common programming  naming conventions.
-- | -- | --

I ran into a generator that followed that convention, and ended up with some broken code.  I think since the spec recommends that `operationId` follows common programming naming conventions, it should be fixed here rather than in the generator.

**Comment by sverch** [comment]
Oh, here it is [in the definition](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/amazonaws.com/iam/2010-05-08/openapi.yaml):

```
paths:
  '/#Action=AddClientIDToOpenIDConnectProvider':
    get:
      x-aws-operation-name: AddClientIDToOpenIDConnectProvider
      operationId: GET AddClientIDToOpenIDConnectProvider
```
