### ISSUE TITLE
Body in PutObject, UploadPart API's type should by string instead of object

### ISSUE THREAD

**Issue by Xuanwo** [APIs-guru/aws2openapi#38]
May be we should convert following pattern:

```yaml
schema:
  type: object
  properties:
    Body:
      description: Object data.
      type: string
```

to

```yaml
schema:
  type: string
  format: binary
```

PutObject 's body should be content of this object in sequence of octets
